USE EmplyMangment;

CREATE TABLE Employees (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME NVARCHAR(50),
    LAST_NAME NVARCHAR(50),
    EMAIL NVARCHAR(50),
    PHONE_NUMBER NVARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID NVARCHAR(20),
    SALARY DECIMAL(10,2),
    COMMISSION_PCT DECIMAL(5,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);
